# airflow/Dockerfile
FROM apache/airflow:2.9.1-python3.10

# Instala dependências
RUN pip install boto3

# Copia DAGs e entrypoint
COPY dags/ /opt/airflow/dags/
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
